# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Naming.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 516)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit_Log = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_Log.setGeometry(QtCore.QRect(390, 10, 321, 391))
        self.textEdit_Log.setObjectName("textEdit_Log")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 371, 391))
        self.groupBox.setObjectName("groupBox")
        self.spinBox_NameCount_Max = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_NameCount_Max.setGeometry(QtCore.QRect(240, 300, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_NameCount_Max.setFont(font)
        self.spinBox_NameCount_Max.setProperty("value", 20)
        self.spinBox_NameCount_Max.setObjectName("spinBox_NameCount_Max")
        self.checkBox_HalfLuck = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_HalfLuck.setGeometry(QtCore.QRect(20, 350, 61, 31))
        self.checkBox_HalfLuck.setChecked(False)
        self.checkBox_HalfLuck.setObjectName("checkBox_HalfLuck")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(210, 300, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.spinBox_NameCount_Min = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_NameCount_Min.setGeometry(QtCore.QRect(140, 300, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_NameCount_Min.setFont(font)
        self.spinBox_NameCount_Min.setProperty("value", 5)
        self.spinBox_NameCount_Min.setObjectName("spinBox_NameCount_Min")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(140, 30, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 80, 327, 211))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.checkBox_Sky_Gold = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_Sky_Gold.setFont(font)
        self.checkBox_Sky_Gold.setObjectName("checkBox_Sky_Gold")
        self.gridLayout.addWidget(self.checkBox_Sky_Gold, 0, 1, 1, 1)
        self.checkBox_Sky_Fire = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_Sky_Fire.setFont(font)
        self.checkBox_Sky_Fire.setChecked(True)
        self.checkBox_Sky_Fire.setObjectName("checkBox_Sky_Fire")
        self.gridLayout.addWidget(self.checkBox_Sky_Fire, 0, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.checkBox_Sky_Water = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_Sky_Water.setFont(font)
        self.checkBox_Sky_Water.setObjectName("checkBox_Sky_Water")
        self.gridLayout.addWidget(self.checkBox_Sky_Water, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.checkBox_Sky_Wood = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_Sky_Wood.setFont(font)
        self.checkBox_Sky_Wood.setObjectName("checkBox_Sky_Wood")
        self.gridLayout.addWidget(self.checkBox_Sky_Wood, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.checkBox_Sky_Earth = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_Sky_Earth.setFont(font)
        self.checkBox_Sky_Earth.setObjectName("checkBox_Sky_Earth")
        self.gridLayout.addWidget(self.checkBox_Sky_Earth, 0, 5, 1, 1)
        self.checkBox_Ground_Gold = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_Ground_Gold.setFont(font)
        self.checkBox_Ground_Gold.setObjectName("checkBox_Ground_Gold")
        self.gridLayout.addWidget(self.checkBox_Ground_Gold, 1, 1, 1, 1)
        self.checkBox_Person_Gold = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_Person_Gold.setFont(font)
        self.checkBox_Person_Gold.setObjectName("checkBox_Person_Gold")
        self.gridLayout.addWidget(self.checkBox_Person_Gold, 2, 1, 1, 1)
        self.checkBox_Destiny_Gold = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_Destiny_Gold.setFont(font)
        self.checkBox_Destiny_Gold.setChecked(True)
        self.checkBox_Destiny_Gold.setObjectName("checkBox_Destiny_Gold")
        self.gridLayout.addWidget(self.checkBox_Destiny_Gold, 3, 1, 1, 1)
        self.checkBox_Fate_Gold = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_Fate_Gold.setFont(font)
        self.checkBox_Fate_Gold.setChecked(True)
        self.checkBox_Fate_Gold.setObjectName("checkBox_Fate_Gold")
        self.gridLayout.addWidget(self.checkBox_Fate_Gold, 4, 1, 1, 1)
        self.checkBox_Ground_Wood = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_Ground_Wood.setFont(font)
        self.checkBox_Ground_Wood.setChecked(True)
        self.checkBox_Ground_Wood.setObjectName("checkBox_Ground_Wood")
        self.gridLayout.addWidget(self.checkBox_Ground_Wood, 1, 2, 1, 1)
        self.checkBox_Person_Wood = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_Person_Wood.setFont(font)
        self.checkBox_Person_Wood.setChecked(True)
        self.checkBox_Person_Wood.setObjectName("checkBox_Person_Wood")
        self.gridLayout.addWidget(self.checkBox_Person_Wood, 2, 2, 1, 1)
        self.checkBox_Destiny_Wood = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_Destiny_Wood.setFont(font)
        self.checkBox_Destiny_Wood.setChecked(True)
        self.checkBox_Destiny_Wood.setObjectName("checkBox_Destiny_Wood")
        self.gridLayout.addWidget(self.checkBox_Destiny_Wood, 3, 2, 1, 1)
        self.checkBox_Fate_Wood = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_Fate_Wood.setFont(font)
        self.checkBox_Fate_Wood.setChecked(True)
        self.checkBox_Fate_Wood.setObjectName("checkBox_Fate_Wood")
        self.gridLayout.addWidget(self.checkBox_Fate_Wood, 4, 2, 1, 1)
        self.checkBox_Ground_Water = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_Ground_Water.setFont(font)
        self.checkBox_Ground_Water.setObjectName("checkBox_Ground_Water")
        self.gridLayout.addWidget(self.checkBox_Ground_Water, 1, 3, 1, 1)
        self.checkBox_Person_Water = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_Person_Water.setFont(font)
        self.checkBox_Person_Water.setObjectName("checkBox_Person_Water")
        self.gridLayout.addWidget(self.checkBox_Person_Water, 2, 3, 1, 1)
        self.checkBox_Destiny_Water = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_Destiny_Water.setFont(font)
        self.checkBox_Destiny_Water.setObjectName("checkBox_Destiny_Water")
        self.gridLayout.addWidget(self.checkBox_Destiny_Water, 3, 3, 1, 1)
        self.checkBox_Fate_Water = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_Fate_Water.setFont(font)
        self.checkBox_Fate_Water.setObjectName("checkBox_Fate_Water")
        self.gridLayout.addWidget(self.checkBox_Fate_Water, 4, 3, 1, 1)
        self.checkBox_Ground_Fire = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_Ground_Fire.setFont(font)
        self.checkBox_Ground_Fire.setChecked(True)
        self.checkBox_Ground_Fire.setObjectName("checkBox_Ground_Fire")
        self.gridLayout.addWidget(self.checkBox_Ground_Fire, 1, 4, 1, 1)
        self.checkBox_Person_Fire = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_Person_Fire.setFont(font)
        self.checkBox_Person_Fire.setChecked(True)
        self.checkBox_Person_Fire.setObjectName("checkBox_Person_Fire")
        self.gridLayout.addWidget(self.checkBox_Person_Fire, 2, 4, 1, 1)
        self.checkBox_Destiny_Fire = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_Destiny_Fire.setFont(font)
        self.checkBox_Destiny_Fire.setChecked(True)
        self.checkBox_Destiny_Fire.setObjectName("checkBox_Destiny_Fire")
        self.gridLayout.addWidget(self.checkBox_Destiny_Fire, 3, 4, 1, 1)
        self.checkBox_Fate_Fire = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_Fate_Fire.setFont(font)
        self.checkBox_Fate_Fire.setChecked(True)
        self.checkBox_Fate_Fire.setObjectName("checkBox_Fate_Fire")
        self.gridLayout.addWidget(self.checkBox_Fate_Fire, 4, 4, 1, 1)
        self.checkBox_Ground_Earth = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_Ground_Earth.setFont(font)
        self.checkBox_Ground_Earth.setObjectName("checkBox_Ground_Earth")
        self.gridLayout.addWidget(self.checkBox_Ground_Earth, 1, 5, 1, 1)
        self.checkBox_Person_Earth = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_Person_Earth.setFont(font)
        self.checkBox_Person_Earth.setObjectName("checkBox_Person_Earth")
        self.gridLayout.addWidget(self.checkBox_Person_Earth, 2, 5, 1, 1)
        self.checkBox_Destiny_Earth = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_Destiny_Earth.setFont(font)
        self.checkBox_Destiny_Earth.setChecked(True)
        self.checkBox_Destiny_Earth.setObjectName("checkBox_Destiny_Earth")
        self.gridLayout.addWidget(self.checkBox_Destiny_Earth, 3, 5, 1, 1)
        self.checkBox_Fate_Earth = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_Fate_Earth.setFont(font)
        self.checkBox_Fate_Earth.setChecked(True)
        self.checkBox_Fate_Earth.setObjectName("checkBox_Fate_Earth")
        self.gridLayout.addWidget(self.checkBox_Fate_Earth, 4, 5, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(20, 300, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.checkBox_Luck = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Luck.setEnabled(False)
        self.checkBox_Luck.setGeometry(QtCore.QRect(90, 350, 61, 31))
        self.checkBox_Luck.setCheckable(True)
        self.checkBox_Luck.setChecked(True)
        self.checkBox_Luck.setObjectName("checkBox_Luck")
        self.spinBox_LastNameCount = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_LastNameCount.setGeometry(QtCore.QRect(180, 30, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_LastNameCount.setFont(font)
        self.spinBox_LastNameCount.setProperty("value", 12)
        self.spinBox_LastNameCount.setObjectName("spinBox_LastNameCount")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 30, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_LastName = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_LastName.setGeometry(QtCore.QRect(60, 30, 41, 41))
        self.lineEdit_LastName.setMaxLength(1)
        self.lineEdit_LastName.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_LastName.setObjectName("lineEdit_LastName")
        self.radioButton_Gender_Boy = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_Gender_Boy.setGeometry(QtCore.QRect(260, 30, 75, 16))
        self.radioButton_Gender_Boy.setObjectName("radioButton_Gender_Boy")
        self.radioButton_Gender_Girl = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_Gender_Girl.setGeometry(QtCore.QRect(260, 60, 75, 16))
        self.radioButton_Gender_Girl.setChecked(True)
        self.radioButton_Gender_Girl.setObjectName("radioButton_Gender_Girl")
        self.pushButton_SelectFullName = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_SelectFullName.setGeometry(QtCore.QRect(540, 410, 171, 71))
        self.pushButton_SelectFullName.setObjectName("pushButton_SelectFullName")
        self.pushButton_SelectNameWord = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_SelectNameWord.setGeometry(QtCore.QRect(280, 410, 161, 71))
        self.pushButton_SelectNameWord.setObjectName("pushButton_SelectNameWord")
        self.pushButton_GetNameCount = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_GetNameCount.setGeometry(QtCore.QRect(10, 410, 171, 71))
        self.pushButton_GetNameCount.setObjectName("pushButton_GetNameCount")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "設定"))
        self.checkBox_HalfLuck.setText(_translate("MainWindow", "半吉"))
        self.label_9.setText(_translate("MainWindow", "~"))
        self.label_7.setText(_translate("MainWindow", "筆劃"))
        self.label_3.setText(_translate("MainWindow", "人"))
        self.checkBox_Sky_Gold.setText(_translate("MainWindow", "金"))
        self.checkBox_Sky_Fire.setText(_translate("MainWindow", "火"))
        self.label.setText(_translate("MainWindow", "天"))
        self.checkBox_Sky_Water.setText(_translate("MainWindow", "水"))
        self.label_2.setText(_translate("MainWindow", "地"))
        self.label_5.setText(_translate("MainWindow", "外"))
        self.checkBox_Sky_Wood.setText(_translate("MainWindow", "木"))
        self.label_4.setText(_translate("MainWindow", "總"))
        self.checkBox_Sky_Earth.setText(_translate("MainWindow", "土"))
        self.checkBox_Ground_Gold.setText(_translate("MainWindow", "金"))
        self.checkBox_Person_Gold.setText(_translate("MainWindow", "金"))
        self.checkBox_Destiny_Gold.setText(_translate("MainWindow", "金"))
        self.checkBox_Fate_Gold.setText(_translate("MainWindow", "金"))
        self.checkBox_Ground_Wood.setText(_translate("MainWindow", "木"))
        self.checkBox_Person_Wood.setText(_translate("MainWindow", "木"))
        self.checkBox_Destiny_Wood.setText(_translate("MainWindow", "木"))
        self.checkBox_Fate_Wood.setText(_translate("MainWindow", "木"))
        self.checkBox_Ground_Water.setText(_translate("MainWindow", "水"))
        self.checkBox_Person_Water.setText(_translate("MainWindow", "水"))
        self.checkBox_Destiny_Water.setText(_translate("MainWindow", "水"))
        self.checkBox_Fate_Water.setText(_translate("MainWindow", "水"))
        self.checkBox_Ground_Fire.setText(_translate("MainWindow", "火"))
        self.checkBox_Person_Fire.setText(_translate("MainWindow", "火"))
        self.checkBox_Destiny_Fire.setText(_translate("MainWindow", "火"))
        self.checkBox_Fate_Fire.setText(_translate("MainWindow", "火"))
        self.checkBox_Ground_Earth.setText(_translate("MainWindow", "土"))
        self.checkBox_Person_Earth.setText(_translate("MainWindow", "土"))
        self.checkBox_Destiny_Earth.setText(_translate("MainWindow", "土"))
        self.checkBox_Fate_Earth.setText(_translate("MainWindow", "土"))
        self.label_8.setText(_translate("MainWindow", "筆劃範圍(小~大)"))
        self.checkBox_Luck.setText(_translate("MainWindow", "吉"))
        self.label_6.setText(_translate("MainWindow", "姓氏"))
        self.lineEdit_LastName.setText(_translate("MainWindow", "邱"))
        self.radioButton_Gender_Boy.setText(_translate("MainWindow", "男生"))
        self.radioButton_Gender_Girl.setText(_translate("MainWindow", "女生"))
        self.pushButton_SelectFullName.setText(_translate("MainWindow", "3. 選取名字"))
        self.pushButton_SelectNameWord.setText(_translate("MainWindow", "2. 取得文字"))
        self.pushButton_GetNameCount.setText(_translate("MainWindow", "1. 筆劃選擇"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
