# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Naming.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(690, 345)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setContentsMargins(-1, -1, -1, 0)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(400, 260))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 381, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.lineEdit_LastName = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_LastName.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_LastName.sizePolicy().hasHeightForWidth())
        self.lineEdit_LastName.setSizePolicy(sizePolicy)
        self.lineEdit_LastName.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_LastName.setMaxLength(1)
        self.lineEdit_LastName.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_LastName.setObjectName("lineEdit_LastName")
        self.horizontalLayout_3.addWidget(self.lineEdit_LastName)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.spinBox_LastNameCount = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_LastNameCount.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_LastNameCount.sizePolicy().hasHeightForWidth())
        self.spinBox_LastNameCount.setSizePolicy(sizePolicy)
        self.spinBox_LastNameCount.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_LastNameCount.setFont(font)
        self.spinBox_LastNameCount.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_LastNameCount.setProperty("value", 12)
        self.spinBox_LastNameCount.setObjectName("spinBox_LastNameCount")
        self.horizontalLayout_3.addWidget(self.spinBox_LastNameCount)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.radioButton_Gender_Boy = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_Gender_Boy.sizePolicy().hasHeightForWidth())
        self.radioButton_Gender_Boy.setSizePolicy(sizePolicy)
        self.radioButton_Gender_Boy.setObjectName("radioButton_Gender_Boy")
        self.horizontalLayout_3.addWidget(self.radioButton_Gender_Boy)
        self.radioButton_Gender_Girl = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_Gender_Girl.sizePolicy().hasHeightForWidth())
        self.radioButton_Gender_Girl.setSizePolicy(sizePolicy)
        self.radioButton_Gender_Girl.setChecked(True)
        self.radioButton_Gender_Girl.setObjectName("radioButton_Gender_Girl")
        self.horizontalLayout_3.addWidget(self.radioButton_Gender_Girl)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 2)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_3.setStretch(3, 2)
        self.horizontalLayout_3.setStretch(4, 1)
        self.horizontalLayout_3.setStretch(5, 1)
        self.horizontalLayout_3.setStretch(6, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.spinBox_FiveLevel_Threshold = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_FiveLevel_Threshold.sizePolicy().hasHeightForWidth())
        self.spinBox_FiveLevel_Threshold.setSizePolicy(sizePolicy)
        self.spinBox_FiveLevel_Threshold.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_FiveLevel_Threshold.setFont(font)
        self.spinBox_FiveLevel_Threshold.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_FiveLevel_Threshold.setMinimum(60)
        self.spinBox_FiveLevel_Threshold.setMaximum(70)
        self.spinBox_FiveLevel_Threshold.setSingleStep(10)
        self.spinBox_FiveLevel_Threshold.setProperty("value", 70)
        self.spinBox_FiveLevel_Threshold.setObjectName("spinBox_FiveLevel_Threshold")
        self.horizontalLayout_4.addWidget(self.spinBox_FiveLevel_Threshold)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.spinBox_NameCount_Min = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_NameCount_Min.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_NameCount_Min.setFont(font)
        self.spinBox_NameCount_Min.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_NameCount_Min.setMinimum(1)
        self.spinBox_NameCount_Min.setMaximum(30)
        self.spinBox_NameCount_Min.setProperty("value", 5)
        self.spinBox_NameCount_Min.setObjectName("spinBox_NameCount_Min")
        self.horizontalLayout_5.addWidget(self.spinBox_NameCount_Min)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.spinBox_NameCount_Max = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_NameCount_Max.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_NameCount_Max.setFont(font)
        self.spinBox_NameCount_Max.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_NameCount_Max.setMinimum(1)
        self.spinBox_NameCount_Max.setMaximum(30)
        self.spinBox_NameCount_Max.setProperty("value", 15)
        self.spinBox_NameCount_Max.setObjectName("spinBox_NameCount_Max")
        self.horizontalLayout_5.addWidget(self.spinBox_NameCount_Max)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.checkBox_HalfLuck = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_HalfLuck.setChecked(False)
        self.checkBox_HalfLuck.setObjectName("checkBox_HalfLuck")
        self.horizontalLayout_6.addWidget(self.checkBox_HalfLuck)
        self.checkBox_Luck = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_Luck.setEnabled(False)
        self.checkBox_Luck.setCheckable(True)
        self.checkBox_Luck.setChecked(True)
        self.checkBox_Luck.setObjectName("checkBox_Luck")
        self.horizontalLayout_6.addWidget(self.checkBox_Luck)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_GetNameCount = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_GetNameCount.sizePolicy().hasHeightForWidth())
        self.pushButton_GetNameCount.setSizePolicy(sizePolicy)
        self.pushButton_GetNameCount.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_GetNameCount.setObjectName("pushButton_GetNameCount")
        self.horizontalLayout.addWidget(self.pushButton_GetNameCount)
        self.pushButton_SelectNameWord = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_SelectNameWord.sizePolicy().hasHeightForWidth())
        self.pushButton_SelectNameWord.setSizePolicy(sizePolicy)
        self.pushButton_SelectNameWord.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_SelectNameWord.setObjectName("pushButton_SelectNameWord")
        self.horizontalLayout.addWidget(self.pushButton_SelectNameWord)
        self.pushButton_SelectFullName = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_SelectFullName.sizePolicy().hasHeightForWidth())
        self.pushButton_SelectFullName.setSizePolicy(sizePolicy)
        self.pushButton_SelectFullName.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_SelectFullName.setObjectName("pushButton_SelectFullName")
        self.horizontalLayout.addWidget(self.pushButton_SelectFullName)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.textEdit_Log = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_Log.sizePolicy().hasHeightForWidth())
        self.textEdit_Log.setSizePolicy(sizePolicy)
        self.textEdit_Log.setMinimumSize(QtCore.QSize(200, 0))
        self.textEdit_Log.setObjectName("textEdit_Log")
        self.gridLayout.addWidget(self.textEdit_Log, 0, 1, 2, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "設定"))
        self.label_6.setText(_translate("MainWindow", "姓氏"))
        self.lineEdit_LastName.setText(_translate("MainWindow", "邱"))
        self.label_7.setText(_translate("MainWindow", "筆劃"))
        self.radioButton_Gender_Boy.setText(_translate("MainWindow", "男生"))
        self.radioButton_Gender_Girl.setText(_translate("MainWindow", "女生"))
        self.label_10.setText(_translate("MainWindow", "五格 - 門檻值設定 (60或70) "))
        self.label_8.setText(_translate("MainWindow", "筆劃範圍(小~大) "))
        self.label_9.setText(_translate("MainWindow", "~"))
        self.label_11.setText(_translate("MainWindow", "筆劃總合 "))
        self.checkBox_HalfLuck.setText(_translate("MainWindow", "半吉"))
        self.checkBox_Luck.setText(_translate("MainWindow", "吉"))
        self.pushButton_GetNameCount.setText(_translate("MainWindow", "1. 筆劃選擇"))
        self.pushButton_SelectNameWord.setText(_translate("MainWindow", "2. 取得文字"))
        self.pushButton_SelectFullName.setText(_translate("MainWindow", "3. 選取名字"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
