# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Naming.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(662, 348)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit_Log = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_Log.setGeometry(QtCore.QRect(400, 10, 251, 321))
        self.textEdit_Log.setObjectName("textEdit_Log")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 381, 241))
        self.groupBox.setObjectName("groupBox")
        self.spinBox_NameCount_Max = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_NameCount_Max.setGeometry(QtCore.QRect(240, 150, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_NameCount_Max.setFont(font)
        self.spinBox_NameCount_Max.setMinimum(1)
        self.spinBox_NameCount_Max.setMaximum(30)
        self.spinBox_NameCount_Max.setProperty("value", 15)
        self.spinBox_NameCount_Max.setObjectName("spinBox_NameCount_Max")
        self.checkBox_HalfLuck = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_HalfLuck.setGeometry(QtCore.QRect(100, 200, 61, 41))
        self.checkBox_HalfLuck.setChecked(False)
        self.checkBox_HalfLuck.setObjectName("checkBox_HalfLuck")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(210, 150, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.spinBox_NameCount_Min = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_NameCount_Min.setGeometry(QtCore.QRect(140, 150, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_NameCount_Min.setFont(font)
        self.spinBox_NameCount_Min.setMinimum(1)
        self.spinBox_NameCount_Min.setMaximum(30)
        self.spinBox_NameCount_Min.setProperty("value", 5)
        self.spinBox_NameCount_Min.setObjectName("spinBox_NameCount_Min")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(110, 30, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(20, 150, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.checkBox_Luck = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Luck.setEnabled(False)
        self.checkBox_Luck.setGeometry(QtCore.QRect(170, 200, 41, 41))
        self.checkBox_Luck.setCheckable(True)
        self.checkBox_Luck.setChecked(True)
        self.checkBox_Luck.setObjectName("checkBox_Luck")
        self.spinBox_LastNameCount = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_LastNameCount.setEnabled(False)
        self.spinBox_LastNameCount.setGeometry(QtCore.QRect(150, 30, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_LastNameCount.setFont(font)
        self.spinBox_LastNameCount.setProperty("value", 12)
        self.spinBox_LastNameCount.setObjectName("spinBox_LastNameCount")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 30, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_LastName = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_LastName.setEnabled(False)
        self.lineEdit_LastName.setGeometry(QtCore.QRect(60, 30, 41, 41))
        self.lineEdit_LastName.setMaxLength(1)
        self.lineEdit_LastName.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_LastName.setObjectName("lineEdit_LastName")
        self.radioButton_Gender_Boy = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_Gender_Boy.setGeometry(QtCore.QRect(220, 30, 75, 16))
        self.radioButton_Gender_Boy.setObjectName("radioButton_Gender_Boy")
        self.radioButton_Gender_Girl = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_Gender_Girl.setGeometry(QtCore.QRect(220, 60, 75, 16))
        self.radioButton_Gender_Girl.setChecked(True)
        self.radioButton_Gender_Girl.setObjectName("radioButton_Gender_Girl")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(20, 90, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.spinBox_FiveLevel_Threshold = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_FiveLevel_Threshold.setGeometry(QtCore.QRect(220, 90, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_FiveLevel_Threshold.setFont(font)
        self.spinBox_FiveLevel_Threshold.setProperty("value", 70)
        self.spinBox_FiveLevel_Threshold.setObjectName("spinBox_FiveLevel_Threshold")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(20, 200, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.pushButton_SelectFullName = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_SelectFullName.setGeometry(QtCore.QRect(270, 260, 120, 71))
        self.pushButton_SelectFullName.setObjectName("pushButton_SelectFullName")
        self.pushButton_SelectNameWord = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_SelectNameWord.setGeometry(QtCore.QRect(140, 260, 120, 71))
        self.pushButton_SelectNameWord.setObjectName("pushButton_SelectNameWord")
        self.pushButton_GetNameCount = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_GetNameCount.setGeometry(QtCore.QRect(10, 260, 120, 71))
        self.pushButton_GetNameCount.setObjectName("pushButton_GetNameCount")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "設定"))
        self.checkBox_HalfLuck.setText(_translate("MainWindow", "半吉"))
        self.label_9.setText(_translate("MainWindow", "~"))
        self.label_7.setText(_translate("MainWindow", "筆劃"))
        self.label_8.setText(_translate("MainWindow", "筆劃範圍(小~大)"))
        self.checkBox_Luck.setText(_translate("MainWindow", "吉"))
        self.label_6.setText(_translate("MainWindow", "姓氏"))
        self.lineEdit_LastName.setText(_translate("MainWindow", "邱"))
        self.radioButton_Gender_Boy.setText(_translate("MainWindow", "男生"))
        self.radioButton_Gender_Girl.setText(_translate("MainWindow", "女生"))
        self.label_10.setText(_translate("MainWindow", "五格 - 門檻值設定 (60或70)"))
        self.label_11.setText(_translate("MainWindow", "筆劃總合"))
        self.pushButton_SelectFullName.setText(_translate("MainWindow", "3. 選取名字"))
        self.pushButton_SelectNameWord.setText(_translate("MainWindow", "2. 取得文字"))
        self.pushButton_GetNameCount.setText(_translate("MainWindow", "1. 筆劃選擇"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
