# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SelectFullName.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_SelectFullName(object):
    def setupUi(self, Form_SelectFullName):
        Form_SelectFullName.setObjectName("Form_SelectFullName")
        Form_SelectFullName.resize(775, 518)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form_SelectFullName.setFont(font)
        self.listWidget_SelectedWord = QtWidgets.QListWidget(Form_SelectFullName)
        self.listWidget_SelectedWord.setEnabled(True)
        self.listWidget_SelectedWord.setGeometry(QtCore.QRect(20, 50, 101, 371))
        self.listWidget_SelectedWord.setObjectName("listWidget_SelectedWord")
        self.listWidget_NameCount = QtWidgets.QListWidget(Form_SelectFullName)
        self.listWidget_NameCount.setGeometry(QtCore.QRect(150, 50, 191, 371))
        self.listWidget_NameCount.setObjectName("listWidget_NameCount")
        self.label_2 = QtWidgets.QLabel(Form_SelectFullName)
        self.label_2.setGeometry(QtCore.QRect(350, 200, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.listWidget_Name1 = QtWidgets.QListWidget(Form_SelectFullName)
        self.listWidget_Name1.setGeometry(QtCore.QRect(400, 50, 61, 371))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listWidget_Name1.setFont(font)
        self.listWidget_Name1.setObjectName("listWidget_Name1")
        self.label_3 = QtWidgets.QLabel(Form_SelectFullName)
        self.label_3.setGeometry(QtCore.QRect(470, 200, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.listWidget_Name2 = QtWidgets.QListWidget(Form_SelectFullName)
        self.listWidget_Name2.setGeometry(QtCore.QRect(500, 50, 61, 371))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listWidget_Name2.setFont(font)
        self.listWidget_Name2.setObjectName("listWidget_Name2")
        self.pushButton_AddFullName = QtWidgets.QPushButton(Form_SelectFullName)
        self.pushButton_AddFullName.setGeometry(QtCore.QRect(570, 200, 51, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.pushButton_AddFullName.setFont(font)
        self.pushButton_AddFullName.setObjectName("pushButton_AddFullName")
        self.listWidget_FullName = QtWidgets.QListWidget(Form_SelectFullName)
        self.listWidget_FullName.setGeometry(QtCore.QRect(630, 50, 121, 371))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listWidget_FullName.setFont(font)
        self.listWidget_FullName.setObjectName("listWidget_FullName")
        self.label_4 = QtWidgets.QLabel(Form_SelectFullName)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 121, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form_SelectFullName)
        self.label_5.setGeometry(QtCore.QRect(150, 20, 191, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form_SelectFullName)
        self.label_6.setGeometry(QtCore.QRect(400, 20, 61, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form_SelectFullName)
        self.label_7.setGeometry(QtCore.QRect(500, 20, 61, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form_SelectFullName)
        self.label_8.setGeometry(QtCore.QRect(650, 20, 81, 20))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.pushButton_AddFullName_2 = QtWidgets.QPushButton(Form_SelectFullName)
        self.pushButton_AddFullName_2.setGeometry(QtCore.QRect(630, 440, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_AddFullName_2.setFont(font)
        self.pushButton_AddFullName_2.setObjectName("pushButton_AddFullName_2")
        self.pushButton_Random = QtWidgets.QPushButton(Form_SelectFullName)
        self.pushButton_Random.setGeometry(QtCore.QRect(30, 450, 75, 41))
        self.pushButton_Random.setObjectName("pushButton_Random")
        self.lineEdit_RandomName = QtWidgets.QLineEdit(Form_SelectFullName)
        self.lineEdit_RandomName.setGeometry(QtCore.QRect(120, 450, 111, 41))
        self.lineEdit_RandomName.setObjectName("lineEdit_RandomName")

        self.retranslateUi(Form_SelectFullName)
        QtCore.QMetaObject.connectSlotsByName(Form_SelectFullName)

    def retranslateUi(self, Form_SelectFullName):
        _translate = QtCore.QCoreApplication.translate
        Form_SelectFullName.setWindowTitle(_translate("Form_SelectFullName", "Select Full Name"))
        self.label_2.setText(_translate("Form_SelectFullName", "=>"))
        self.label_3.setText(_translate("Form_SelectFullName", "+"))
        self.pushButton_AddFullName.setText(_translate("Form_SelectFullName", "->"))
        self.label_4.setText(_translate("Form_SelectFullName", "Selected Words"))
        self.label_5.setText(_translate("Form_SelectFullName", "Name Count"))
        self.label_6.setText(_translate("Form_SelectFullName", "Name 1"))
        self.label_7.setText(_translate("Form_SelectFullName", "Name 2"))
        self.label_8.setText(_translate("Form_SelectFullName", "Full Name"))
        self.pushButton_AddFullName_2.setText(_translate("Form_SelectFullName", "Remove"))
        self.pushButton_Random.setText(_translate("Form_SelectFullName", "Random"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_SelectFullName = QtWidgets.QWidget()
    ui = Ui_Form_SelectFullName()
    ui.setupUi(Form_SelectFullName)
    Form_SelectFullName.show()
    sys.exit(app.exec_())
